version: "3.8"

services:
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://mongodb:27017/your-db-name
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
